# Generated by Django 2.1.7 on 2019-06-03 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20190207_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darksky_historical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(blank=True, default=None, null=True)),
                ('max_uv_index', models.IntegerField(blank=True, default=None, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Location')),
            ],
        ),
    ]
